silder component
GSG-G10/saydat-alard pull request #114
Opened 2021-11-01 05:51 UTC by modrayyes

2021-11-05 18:22 UTC, LinaYahya requested changes

2021-11-05 18:22 UTC, LinaYahya commented on client/src/components/slider/slider.js
> +        throw new Error(`Error in fetching products ${err}`);
turn to async await and message.error to clear text

2021-11-05 18:22 UTC, LinaYahya commented on client/src/App.js
> +      <Slider />
pull the last changes and import Slider in the home page

2021-11-05 18:22 UTC, LinaYahya commented on client/src/components/slider/slider.js
> +import React, { useState, useEffect } from 'react';
rename file to index.js

2021-11-06 09:00 UTC, Nizar7zak approved these changes
Great Job

2021-11-06 09:02 UTC, reemsh2000 approved these changes

2021-11-06 09:08 UTC, LinaYahya approved these changes

2021-11-06 09:19 UTC, merged