Story form
GSG-G10/saydat-alard pull request #125
Opened 2021-11-03 06:08 UTC by modrayyes

2021-11-04 07:35 UTC, NadiaJalalTamimi approved these changes

2021-11-04 08:05 UTC, reemsh2000 approved these changes

2021-11-04 09:02 UTC, Nizar7zak requested changes

2021-11-04 09:02 UTC, Nizar7zak commented on client/src/components/uploadStoryForm/index.js
> +            <button type="button" className="buttonS">
we have a common component button, it takes a class name and text as props

2021-11-04 09:02 UTC, Nizar7zak commented on client/src/components/uploadStoryForm/index.js
> +                <input
here you use input html and in line 77 used Input from antd, just be consist

2021-11-04 10:15 UTC, LinaYahya requested changes

2021-11-04 10:15 UTC, LinaYahya commented on client/src/components/uploadStoryForm/index.js
> +  const [selectedFile, setSelectedFile] = useState();
give it default value

2021-11-04 10:15 UTC, LinaYahya commented on client/src/components/uploadStoryForm/index.js
> +      </Button>
this button will be out of this component, and visible and setVisisble will pass as a props to the component

2021-11-04 10:15 UTC, LinaYahya commented on client/src/components/uploadStoryForm/index.js
> +              <dev className="inputForm">
```suggestion
              <div className="inputForm">
```

2021-11-04 10:15 UTC, LinaYahya commented on client/src/components/uploadStoryForm/index.js
> +          <form onSubmit={handleFileInputChange} className="form">
the form will wrap all our inputs not only file input, although notice that content and title are required in database so those values shouldn't be empty.
As we validate the request body on the server side we need to validate input's here else.
So, If I'm a user trying to submit form with empty values I should see an error message clarify that to me.
https://ant.design/components/form/ check the first example here to add rule to your input

2021-11-04 10:15 UTC, LinaYahya commented on client/src/components/uploadStoryForm/index.js
> +        />
```suggestion
      <Form.Item
        label="اللعنوان"
        name="عنوان"
        rules={[{ required: true, message: 'أضف عنواناً لقصتك' }]}
      >
        <Input
          onChange={(e) => setStory((prev) => ({ ...prev, title: e.target.value }))}
          placeholder="العنوان"
        />
        <Form.Item />
```

2021-11-04 10:15 UTC, LinaYahya commented on client/src/components/uploadStoryForm/index.js
> +          <form onSubmit={handleFileInputChange} className="form">
form onSubmit here will never work,
Instead make a ref to your form and handle onSubmit modal to run this function

2021-11-06 16:46 UTC, Nizar7zak approved these changes
Great Job Mohammed

2021-11-06 17:57 UTC, merged