Add Proverb
GSG-G10/saydat-alard pull request #131
Opened 2021-11-04 06:41 UTC by NadiaJalalTamimi

Make the add proverbs modal in the dashboard router.

![Screenshot (148)](https://user-images.githubusercontent.com/62670964/140269075-0ceefc31-712b-4e6c-8c3a-552419d4f24b.png)

2021-11-04 08:07 UTC, reemsh2000 approved these changes

2021-11-04 08:24 UTC, modrayyes approved these changes

2021-11-04 10:29 UTC, Nizar7zak requested changes

2021-11-04 10:29 UTC, Nizar7zak commented on client/src/components/Proverbs/Addproverbs.jsx
> +  const [value, setValue] = useState({ proverb: '' });
I guess it's better if you set an initial value here like this (' ')

2021-11-04 10:29 UTC, Nizar7zak commented on client/src/components/Proverbs/Addproverbs.jsx
> +      console.log(error);
you should avoid any console line in your code. I guess you forget remove it.

2021-11-04 10:29 UTC, Nizar7zak commented on client/src/components/Proverbs/Addproverbs.jsx
> +          <div><Input type="text" onChange={handleChange} className="input" placeholder="أضف هنا المثال" required /></div>
why you nested an input component with div? you can style an input it took class name

2021-11-04 10:29 UTC, Nizar7zak commented on client/src/components/Proverbs/Addproverbs.jsx
> +            <Button size="large" type="primary" onClick={handleOpen} style={{ backgroundColor: 'rgb(24, 85, 3)', borderRadius: '8px', padding: '0px 40px' }}>
here you should use our common button component,

2021-11-04 10:29 UTC, Nizar7zak commented on client/src/components/Proverbs/proverb.css
> +    height: 270px;
avoid px value, you should set an relative value like vh.

2021-11-04 11:34 UTC, LinaYahya requested changes

2021-11-04 11:34 UTC, LinaYahya commented on client/src/components/Proverbs/Addproverbs.jsx
> +        throw new Error('يجب عليك إضافة مثل');
why to throw instead use messsgae.warn here,
OR I prefer to validate input using Form.Item

2021-11-04 11:34 UTC, LinaYahya commented on client/src/components/Proverbs/Addproverbs.jsx
> +      </Button>
remove this button and pass visible and setVisible as a props

2021-11-04 11:34 UTC, LinaYahya commented on client/src/components/Proverbs/Addproverbs.jsx
> +        <div className="proverbcontainer">
Check how to add form to modal we'll use antd Form instead

2021-11-04 13:56 UTC, LinaYahya approved these changes

2021-11-04 15:15 UTC, modrayyes approved these changes

2021-11-05 17:46 UTC, LinaYahya approved these changes

2021-11-06 08:13 UTC, Nizar7zak approved these changes

2021-11-06 08:15 UTC, merged