Log In
GSG-G10/saydat-alard pull request #132
Opened 2021-11-04 07:17 UTC by NadiaJalalTamimi

make the login component page.

![Screenshot (150)](https://user-images.githubusercontent.com/62670964/140272577-38c70c30-5288-4783-bcab-f1e7d07d68fb.png)

2021-11-04 08:12 UTC, modrayyes approved these changes

2021-11-04 10:32 UTC, Nizar7zak requested changes

2021-11-04 10:32 UTC, Nizar7zak commented on client/src/pages/Login.jsx
> +          <h1>تسجيـــل الــدخول</h1>
here you should use our title common component !

2021-11-04 10:32 UTC, Nizar7zak commented on client/src/pages/Login.jsx
> +        <div><img className="loginImg" src={flower} alt="flower" /></div>
here you should use our Img common component,

2021-11-04 10:32 UTC, Nizar7zak commented on client/src/pages/Login.jsx
> +            <Form.Item
you can destruct Item from Form, I think it's better if we destruct it.

2021-11-04 11:39 UTC, LinaYahya requested changes

2021-11-04 11:39 UTC, LinaYahya commented on client/src/pages/Login.jsx
> +            </a>
```suggestion
            <Link to="/signup">
              إنشاء حساب
            </Link>
```
and import link from react-router-dom

2021-11-05 17:45 UTC, LinaYahya requested changes

2021-11-05 17:45 UTC, LinaYahya commented on client/src/index.js
> +      <Login />
```suggestion
```

2021-11-05 17:45 UTC, LinaYahya commented on client/src/pages/Login.jsx
> +// import Title from '../components/common/Title';
```suggestion
```
remove commented lines

2021-11-05 17:45 UTC, LinaYahya commented on client/src/pages/Login.jsx
> +import './login.css';
make a folder for login and put your files there

2021-11-05 17:45 UTC, LinaYahya commented on client/src/pages/Login.jsx
> +          history.push('/');
Good Job Nadia,
we do need to setUser to user from the authProvider, so maybe we'll need to send user data from the server so we can setUser({id, name, role})

2021-11-05 17:45 UTC, LinaYahya commented on client/src/pages/Login.jsx
> +            <a href="/signup">
```suggestion
            <Link to="/signup">
```

2021-11-06 09:27 UTC, Nizar7zak approved these changes

2021-11-06 10:07 UTC, merged